server:
  port: 8088
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangweitest/spring-cloud-config.git      # 配置Git仓库的地址
#          username:                                                          # Git仓库的账号
#          password:                                                         # Git仓库的密码