server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: eurekaservice1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
